// Generated by protoc-gen-twirp_typescript. DO NOT EDIT
import Axios from 'axios';
import { createTwirpAdapter } from 'pbjs-twirp';
import { floqars } from './nearby.pb';

const getServiceMethodName = (fn: any): string => {
    if (fn === floqars.services.nearby.Nearby.prototype.findNearby) {
        return 'FindNearby';
    }
    if (fn === floqars.services.nearby.Nearby.prototype.updateLocation) {
        return 'UpdateLocation';
    }

    throw new Error('Unknown Method');
};

export const NearbyPathPrefix = '/twirp/floqars.services.nearby.Nearby/';

export const createNearby = (baseURL: string): floqars.services.nearby.Nearby => {
    const axios = Axios.create({
        baseURL: baseURL + NearbyPathPrefix,
        headers: {
            Accept: 'application/protobuf'
        }
    });

    return floqars.services.nearby.Nearby.create(createTwirpAdapter(axios, getServiceMethodName));
};
