"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// Generated by protoc-gen-twirp_typescript. DO NOT EDIT
const axios_1 = require("axios");
const pbjs_twirp_1 = require("pbjs-twirp");
const nearby_pb_1 = require("./nearby.pb");
const getServiceMethodName = (fn) => {
    if (fn === nearby_pb_1.floqars.services.nearby.Nearby.prototype.findNearby) {
        return 'FindNearby';
    }
    if (fn === nearby_pb_1.floqars.services.nearby.Nearby.prototype.updateLocation) {
        return 'UpdateLocation';
    }
    throw new Error('Unknown Method');
};
exports.NearbyPathPrefix = '/twirp/floqars.services.nearby.Nearby/';
exports.createNearby = (baseURL) => {
    const axios = axios_1.default.create({
        baseURL: baseURL + exports.NearbyPathPrefix,
        headers: {
            Accept: 'application/protobuf'
        }
    });
    return nearby_pb_1.floqars.services.nearby.Nearby.create(pbjs_twirp_1.createTwirpAdapter(axios, getServiceMethodName));
};
